### ISSUE TITLE
save_open not working with joblib

### ISSUE THREAD

**Issue by eugeneteoh** [huggingface/safetensors#328]
### System Info

safetensors v0.3.2
joblib v1.3.2

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Reproduction

```python
import torch
from safetensors import safe_open
from safetensors.torch import save_file
from joblib import Parallel, delayed

tensors = {
   "weight1": torch.zeros((1024, 1024)),
   "weight2": torch.zeros((1024, 1024))
}
save_file(tensors, "model.safetensors")

def test():
    tensors = {}
    with safe_open("model.safetensors", framework="pt", device="cpu") as f:
        for key in f.keys():
            tensors[key] = f.get_tensor(key)


Parallel(n_jobs=2)(delayed(test) for _ in range(10))
```

### Expected behavior

```bash
joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/user/miniconda3/envs/test/lib/python3.10/site-packages/joblib/externals/loky/process_executor.py", line 426, in _process_worker
    call_item = call_queue.get(block=True, timeout=timeout)
  File "/home/user/miniconda3/envs/test/lib/python3.10/multiprocessing/queues.py", line 122, in get
    return _ForkingPickler.loads(res)
AttributeError: type object 'safe_open' has no attribute 'metadata'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/test.py", line 19, in <module>
    Parallel(n_jobs=2)(delayed(test) for _ in range(10))
  File "/home/user/miniconda3/envs/test/lib/python3.10/site-packages/joblib/parallel.py", line 1952, in __call__
    return output if self.return_generator else list(output)
  File "/home/user/miniconda3/envs/test/lib/python3.10/site-packages/joblib/parallel.py", line 1595, in _get_outputs
    yield from self._retrieve()
  File "/home/user/miniconda3/envs/test/lib/python3.10/site-packages/joblib/parallel.py", line 1699, in _retrieve
    self._raise_error_fast()
  File "/home/user/miniconda3/envs/test/lib/python3.10/site-packages/joblib/parallel.py", line 1734, in _raise_error_fast
    error_job.get_result(self.timeout)
  File "/home/user/miniconda3/envs/test/lib/python3.10/site-packages/joblib/parallel.py", line 736, in get_result
    return self._return_or_raise()
  File "/home/user/miniconda3/envs/test/lib/python3.10/site-packages/joblib/parallel.py", line 754, in _return_or_raise
    raise self._result
joblib.externals.loky.process_executor.BrokenProcessPool: A task has failed to un-serialize. Please ensure that the arguments of the function are all picklable.
```

**Comment by Narsil** [comment]
Yes save_open is handling open files...

`open` doesn't work either:

```python
from joblib import Parallel, delayed

def test():
    with open("test.txt") as f:
        print(f.read())


Parallel(n_jobs=2)(delayed(test) for _ in range(10))
```

**Comment by eugeneteoh** [comment]
General question: are there any other good ways of parallelizing safe_open?

So far I found `pathos.multiprocessing` that can serialize this.

**Comment by Narsil** [comment]
Why do you need it ?

`safe_open` is memory mapping the file, leading to most likely the optimal way to read the file (the OS is in charge). Parallelization never helps in that case. Only case where it's subpar is when you're loading from a network mounted disk (you're basically lying to the OS, therefore it's not doing a great job at making the reads sequential which network prefers).

Sending data to your threads/processes AFTER load should be easy enough. (or making you various threads/processes read only the bit of data they are interested in, this is what is done here https://github.com/huggingface/text-generation-inference and we cut load times by a big factor over torch pickle.)

Doc reference: https://huggingface.co/docs/safetensors/index#load-tensors

**Comment by eugeneteoh** [comment]
I'm using safetensors as a data storage format. It's always going to be faster to parallelize pre-processing. I haven't had issues with `pathos` so I'll keep using that.
