### ISSUE TITLE
Problem serializing quantized weights

### ISSUE THREAD

**Issue by sayakpaul** [huggingface/safetensors#515]
Trying to serialize weights quantized with `ao` (https://github.com/pytorch/ao) leads to an error. 

```python
import safetensors.torch
import tempfile
import torch
from torchao.utils import get_model_size_in_bytes
from torchao.quantization.quant_api import (
    quantize_,
    int4_weight_only,
)

class ToyLinearModel(torch.nn.Module):
    def __init__(self, m=64, n=32, k=64):
        super().__init__()
        self.linear1 = torch.nn.Linear(m, n, bias=False)
        self.linear2 = torch.nn.Linear(n, k, bias=False)

    def example_inputs(self, batch_size=1, dtype=torch.float32, device="cpu"):
        return (torch.randn(batch_size, self.linear1.in_features, dtype=dtype, device=device),)

    def forward(self, x):
        x = self.linear1(x)
        x = self.linear2(x)
        return x

dtype = torch.bfloat16
m = ToyLinearModel(1024, 1024, 1024).eval().to(dtype).to("cuda")
print(f"original model size: {get_model_size_in_bytes(m) / 1024 / 1024} MB")

example_inputs = m.example_inputs(dtype=dtype, device="cuda")
quantize_(m, int4_weight_only())
print(f"quantized model size: {get_model_size_in_bytes(m) / 1024 / 1024} MB")

ref = m(*example_inputs)
with tempfile.NamedTemporaryFile() as f:
    safetensors.torch.save_file(m.state_dict(), f)
    f.seek(0)
    state_dict = safetensors.torch.load_file(f)

with torch.device("meta"):
    m_loaded = ToyLinearModel(1024, 1024, 1024).eval().to(dtype)

# `linear.weight` is nn.Parameter, so we check the type of `linear.weight.data`
print(f"type of weight before loading: {type(m_loaded.linear1.weight.data), type(m_loaded.linear2.weight.data)}")
m_loaded.load_state_dict(state_dict, assign=True)
print(f"type of weight after loading: {type(m_loaded.linear1.weight), type(m_loaded.linear2.weight)}")

res = m_loaded(*example_inputs)
assert torch.equal(res, ref)
```

Error:

```bash
Traceback (most recent call last):
  File "/fsx/sayak/pixart_ao.py", line 32, in <module>
    safetensors.torch.save_file(model.state_dict(), f)
  File "/fsx/sayak/miniconda3/envs/diffusers/lib/python3.9/site-packages/safetensors/torch.py", line 281, in save_file
    serialize_file(_flatten(tensors), filename, metadata=metadata)
  File "/fsx/sayak/miniconda3/envs/diffusers/lib/python3.9/site-packages/safetensors/torch.py", line 470, in _flatten
    shared_pointers = _find_shared_tensors(tensors)
  File "/fsx/sayak/miniconda3/envs/diffusers/lib/python3.9/site-packages/safetensors/torch.py", line 72, in _find_shared_tensors
    if v.device != torch.device("meta") and storage_ptr(v) != 0 and storage_size(v) != 0:
  File "/fsx/sayak/miniconda3/envs/diffusers/lib/python3.9/site-packages/safetensors/torch.py", line 17, in storage_ptr
    return tensor.storage().data_ptr()
  File "/fsx/sayak/miniconda3/envs/diffusers/lib/python3.9/site-packages/torch/storage.py", line 1011, in data_ptr
    return self._data_ptr()
  File "/fsx/sayak/miniconda3/envs/diffusers/lib/python3.9/site-packages/torch/storage.py", line 1015, in _data_ptr
    return self._untyped_storage.data_ptr()
RuntimeError: Attempted to access the data pointer on an invalid python storage.
```

I am no safetensors 0.4.2 and PyTorch 2.4.0.

**Comment by Narsil** [comment]
This is not supported, as None of the quantized types share any characteristic similar enough to dedicate code into them.

You need to figure out workarounds, usually that means serializing in pure U8 (bytes) or (INT32, for alignement).

You can check examples here for instance: https://huggingface.co/hugging-quants/Meta-Llama-3.1-70B-Instruct-AWQ-INT4/tree/main (AWQ, Marlin, GPTQ all use similar encoding schemes, with an external configuration)

**Comment by sayakpaul** [comment]
Okay. I posted about this issue here as well for cross-reference:
https://github.com/huggingface/transformers/pull/32306

**Comment by Narsil** [comment]
Closing for now as it's expected behavior.
